# Frontend Development Dockerfile
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY public public
COPY src src
COPY craco.config.js tailwind.config.js postcss.config.js ./
COPY plugins plugins
COPY .env .

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "start"]
